### ISSUE TITLE
Going to error in new 

### ISSUE THREAD

**Issue by shelu16** [zhzyker/vulmap#18]
root@server:~/tools/vulmap# python3 vulmap.py -u https://paypal.com
Traceback (most recent call last):
  File "vulmap.py", line 8, in <module>                               from gevent import monkey;monkey.patch_all()
  File "/usr/local/lib/python3.6/dist-packages/gevent/monkey.py", line 1214, in patch_all                                               _notify_patch(events.GeventWillPatchAllEvent(modules_to_patch, kwargs), _warnings)
  File "/usr/local/lib/python3.6/dist-packages/gevent/monkey.py", line 185, in _notify_patch                                            notify_and_call_entry_points(event)
  File "/usr/local/lib/python3.6/dist-packages/gevent/events.py", line 104, in notify_and_call_entry_points
    subscriber = plugin.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2323, in load
    self.require(*args, **kwargs)                                   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2346, in require                                                items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 783, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.VersionConflict: (psutil 5.6.7 (/usr/local/lib/python3.6/dist-packages), Requirement.parse('psutil>=5.7.0; sys_platform != "win32" or platform_python_implementation == "CPython" and extra == "monitor"'))                                               root@server:~/tools/vulmap

**Comment by shelu16** [comment]
root@server:~/tools/vulmap# python vulmap.py -u https://paypal.com                                                                    File "vulmap.py", line 261
    color.magenta(pocname)),end="                    \r",flush = True)
                               ^

**Comment by shelu16** [comment]
Resolve issue with sudo pip install gevent

**Comment by shelu16** [comment]
Iys running fast and nice

**Comment by zhzyker** [comment]
yep
new features require new dependencies
