### ISSUE TITLE
运行时报错

### ISSUE THREAD

**Issue by zzz6792x** [zhzyker/vulmap#31]
TypeError: an integer is required (got type bytes)

**Comment by zhzyker** [comment]
麻烦师傅贴一哈完整报错
我不晓得具体哪里出的问题

**Comment by zzz6792x** [comment]
[  |                              
  _   __  __   _   | |  _ .--..--.   ,--.  _ .--.   
 [ \ [  ][  | | |  | | [ `.-. .-. | `'_\ :[ '/'`\ \ 
  \ \/ /  | \_/ |, | |  | | | | | | // | |,| \__/ | 
   \__/   '.__.'_/[___][___||__||__]'-;__/| ;.___/  
                                          [__|

[10:05:41] [INFO] Currently the latest version: 0.6
Traceback (most recent call last):
  File "vulmap.py", line 91, in <module>
    core.control_options(args)  # 运行核心选项控制方法用于处理不同选项并开始扫描
  File "/root/桌面/scan/vulmap/core/core.py", line 41, in control_options
    ceye()  # 测试ceye连接性
  File "/root/桌面/scan/vulmap/module/api/ceye.py", line 16, in ceye
    res = requests.get(api_url, headers=headers, timeout=timeout, verify=False)
  File "/usr/local/lib/python3.8/dist-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py", line 600, in urlopen
    httplib_response = self._make_request(conn, method, url,
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py", line 355, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.8/http/client.py", line 1255, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1301, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1250, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1010, in _send_output
    self.send(msg)
  File "/usr/lib/python3.8/http/client.py", line 950, in send
    self.connect()
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connection.py", line 183, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connection.py", line 159, in _new_conn
    conn = connection.create_connection(
  File "/usr/local/lib/python3.8/dist-packages/urllib3/util/connection.py", line 57, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/local/lib/python3.8/dist-packages/gevent/_socketcommon.py", line 212, in getaddrinfo
    addrlist = get_hub().resolver.getaddrinfo(host, port, family, type, proto, flags)
  File "/usr/local/lib/python3.8/dist-packages/gevent/resolver/thread.py", line 65, in getaddrinfo
    return self.pool.apply(_socket.getaddrinfo, args, kwargs)
  File "/usr/local/lib/python3.8/dist-packages/gevent/pool.py", line 159, in apply
    return self.spawn(func, *args, **kwds).get()
  File "src/gevent/event.py", line 268, in gevent._event.AsyncResult.get
  File "src/gevent/event.py", line 296, in gevent._event.AsyncResult.get
  File "src/gevent/event.py", line 286, in gevent._event.AsyncResult.get
  File "src/gevent/event.py", line 266, in gevent._event.AsyncResult._raise_exception
  File "src/gevent/event.py", line 211, in gevent._event.AsyncResult.exc_info.__get__
  File "/usr/local/lib/python3.8/dist-packages/gevent/_tblib.py", line 371, in g
    return f(a)
  File "/usr/local/lib/python3.8/dist-packages/gevent/_tblib.py", line 432, in load_traceback
    return loads(s)
  File "/usr/local/lib/python3.8/dist-packages/gevent/_tblib.py", line 337, in unpickle_traceback
    return ret.as_traceback()
  File "/usr/local/lib/python3.8/dist-packages/gevent/_tblib.py", line 202, in as_traceback
    code = CodeType(
TypeError: an integer is required (got type bytes)

**Comment by zhzyker** [comment]
这个问题因为ceye.io现在无法访问导致的。已经再  https://github.com/zhzyker/vulmap/issues/29  修复，师傅重新更新一下就好  
目前因为ceye.io未知原因爆炸，回导致fastjson之类的webapps无法检测，下个版本会加入dnslog.cn或更多dns平台以解决ceye不稳定问题

**Comment by zzz6792x** [comment]
可以了  谢谢大师傅
