### ISSUE TITLE
这是啥情况

### ISSUE THREAD

**Issue by zhangpengluanjuan12** [zhzyker/vulmap#45]
```
C:\vulmap-main\vulmap-main>python vulmap.py
                   __
                  [  |
  _   __  __   _   | |  _ .--..--.   ,--.  _ .--.
 [ \ [  ][  | | |  | | [ `.-. .-. | `'_\ :[ '/'`\ \
  \ \/ /  | \_/ |, | |  | | | | | | // | |,| \__/ |
   \__/   '.__.'_/[___][___||__||__]'-;__/| ;.___/
                                          [__|
Traceback (most recent call last):
  File "C:\vulmap-main\vulmap-main\vulmap.py", line 14, in <module>
    from core.core import core
  File "C:\vulmap-main\vulmap-main\core\core.py", line 16, in <module>
    from core.scan import scan
  File "C:\vulmap-main\vulmap-main\core\scan.py", line 12, in <module>
    from payload.OracleWeblogic import OracleWeblogic
ModuleNotFoundError: No module named 'payload.OracleWeblogic'
```

**Comment by zhzyker** [comment]
0.7中已解决 更新一下？

**Comment by zj-xjy** [comment]
@zhzyker                    __
                  [  |
  _   __  __   _   | |  _ .--..--.   ,--.  _ .--.
 [ \ [  ][  | | |  | | [ `.-. .-. | `'_\ :[ '/'`\ \
  \ \/ /  | \_/ |, | |  | | | | | | // | |,| \__/ |
   \__/   '.__.'_/[___][___||__||__]'-;__/| ;.___/
                                          [__|
Traceback (most recent call last):
  File "D:\Desktop\vulmap-main\vulmap-main\vulmap.py", line 67, in <module>
    core.control_options(args)  # 运行核心选项控制方法用于处理不同选项并开始扫描
  File "D:\Desktop\vulmap-main\vulmap-main\core\core.py", line 33, in control_options
    proxy_set(args.http, "http")  # proxy support socks5 http https
  File "D:\Desktop\vulmap-main\vulmap-main\module\proxy.py", line 29, in proxy_set
    proxy_ip_info_json = json.loads(proxy_ip_info.text)
  File "D:\python3.10\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "D:\python3.10\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\python3.10\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
这个错误是依赖错误了吗,版本是python3.11
