### ISSUE TITLE
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'

### ISSUE THREAD

**Issue by xiaofeng9527** [zhzyker/vulmap#6]
## 执行程序报错，0.2版本和0.1版本都有这个错误
```
Traceback (most recent call last):
  File "vulmap.py", line 7609, in <module>
    cmdlineparser(sys.argv)
  File "vulmap.py", line 7568, in cmdlineparser
    Target.allvuln_url(args.url)
  File "vulmap.py", line 7337, in allvuln_url
    Start.allvulnscan(self)
  File "vulmap.py", line 7126, in allvulnscan
    Start.apache_solr(self)
  File "vulmap.py", line 7139, in apache_solr
    PocApacheSolr.cve_2019_0193()
  File "vulmap.py", line 331, in cve_2019_0193
    self.solrhost = self.hostname+":"+str(self.port)
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
```

**Comment by zhzyker** [comment]
emm知道是哪里的问题，0.3中修复

**Comment by xiaofeng9527** [comment]
谢谢你，辛苦了
