### ISSUE TITLE
无法正常运行

### ISSUE THREAD

**Issue by Polestar666** [zhzyker/vulmap#72]
from module.time import now
from module.color import color
from module.banner import banner

大部分都是这个module库不存在

**Comment by zhzyker** [comment]
都是本地库哇 ，有没有完整报错代码

**Comment by Polestar666** [comment]
```
Traceback (most recent call last):
  File "/Users/wangyang/PycharmProjects/SafeTools/vulmap-main/vulmap.py", line 9, in <module>
    require()
  File "/Users/wangyang/PycharmProjects/SafeTools/vulmap-main/module/install.py", line 79, in require
    from gevent import monkey
  File "/Users/wangyang/PycharmProjects/SafeTools/venv/lib/python3.10/site-packages/gevent/__init__.py", line 86, in <module>
    from gevent._hub_local import get_hub
  File "/Users/wangyang/PycharmProjects/SafeTools/venv/lib/python3.10/site-packages/gevent/_hub_local.py", line 101, in <module>
    import_c_accel(globals(), 'gevent.__hub_local')
  File "/Users/wangyang/PycharmProjects/SafeTools/venv/lib/python3.10/site-packages/gevent/_util.py", line 148, in import_c_accel
    mod = importlib.import_module(cname)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "src/gevent/_hub_local.py", line 1, in init gevent._gevent_c_hub_local
ValueError: greenlet.greenlet size changed, may indicate binary incompatibility. Expected 160 from C header, got 40 from PyObject
```

**Comment by zhzyker** [comment]
可能和 gevent 版本有冲突
