### ISSUE TITLE
@zhzyker 大佬这个是为什么呀,python3.11,windows       

### ISSUE THREAD

**Issue by zj-xjy** [zhzyker/vulmap#73]
```
                  [  |
  _   __  __   _   | |  _ .--..--.   ,--.  _ .--.
 [ \ [  ][  | | |  | | [ `.-. .-. | `'_\ :[ '/'`\ \
  \ \/ /  | \_/ |, | |  | | | | | | // | |,| \__/ |
   \__/   '.__.'_/[___][___||__||__]'-;__/| ;.___/
                                          [__|
Traceback (most recent call last):
  File "D:\Desktop\vulmap-main\vulmap-main\vulmap.py", line 67, in <module>
    core.control_options(args)  # 运行核心选项控制方法用于处理不同选项并开始扫描
  File "D:\Desktop\vulmap-main\vulmap-main\core\core.py", line 33, in control_options
    proxy_set(args.http, "http")  # proxy support socks5 http https
  File "D:\Desktop\vulmap-main\vulmap-main\module\proxy.py", line 29, in proxy_set
    proxy_ip_info_json = json.loads(proxy_ip_info.text)
  File "D:\python3.10\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "D:\python3.10\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\python3.10\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by zj-xjy** [comment]
在执行命令: python3 vulmap.py -f url.txt --proxy-http 127.0.0.1:8080的时候会出现这个错误,其他命令没有

**Comment by zj-xjy** [comment]
联动的burp,8080端口burp在用

**Comment by zhzyker** [comment]
参数看着没问题啊

> 在执行命令: python3 vulmap.py -f url.txt --proxy-http 127.0.0.1:8080的时候会出现这个错误,其他命令没有

**Comment by zj-xjy** [comment]
我看着也没问题,但就是找不出错在哪了

> 参数看着没问题啊
> 
> > 在执行命令: python3 vulmap.py -f url.txt --proxy-http 127.0.0.1:8080的时候会出现这个错误,其他命令没有

**Comment by zj-xjy** [comment]
133.xx.xxx.247
133.xx.xxx.247:1000
133.xx.xxx.247:2001
133.xx.xxx.247:3888 
这个是url文件的地址

**Comment by zj-xjy** [comment]
是我大意了,没有加上http,完整的应该是http://xxxxx
感谢大佬的工具

**Comment by zj-xjy** [comment]
我回到家后发现好像不只是因为这个,在用工具前需要把burp代理的拦截打开,然后点回车后burp抓到包后点点取消拦截就可以正常运行了,有点神奇了

> 是我大意了,没有加上http,完整的应该是 [http://xxxxx ](http://xxxxx) 感谢大佬的工具
