### ISSUE TITLE
启动报错No module named 'payload.Exchange'

### ISSUE THREAD

**Issue by dooonabe** [zhzyker/vulmap#78]
windows10 python3.10 或者wsl python3.8都是这个报错
pip3 install -r requirements.txt都成功了，但是启动会报这个错误

Traceback (most recent call last):
  File "D:\project\vulmap\vulmap.py", line 14, in <module>
    from core.core import core
  File "D:\project\vulmap\core\core.py", line 19, in <module>
    from core.scan import scan
  File "D:\project\vulmap\core\scan.py", line 25, in <module>
    from payload.Exchange import Exchange
ModuleNotFoundError: No module named 'payload.Exchange'

**Comment by dooonabe** [comment]
关闭杀软也不行

**Comment by zhzyker** [comment]
> 关闭杀软也不行

因为文件已经被删了

**Comment by dooonabe** [comment]
感谢
