### ISSUE TITLE
Json解析错误

### ISSUE THREAD

**Issue by jidle123** [zhzyker/vulmap#81]
第一次正常运行，第二次开始突然报错，网上找了一堆结果都没什么用，请问这个该怎么处理
Traceback (most recent call last):
  File "vulmap.py", line 67, in <module>
    core.control_options(args)  # 运行核心选项控制方法用于处理不同选项并开始扫描
  File "E:\anti_check\gui_scan\vulmap\core\core.py", line 33, in control_options
    proxy_set(args.http, "http")  # proxy support socks5 http https
  File "E:\anti_check\gui_scan\vulmap\module\proxy.py", line 29, in proxy_set
    proxy_ip_info_json = json.loads(proxy_ip_info.text)
  File "C:\Users\93721\AppData\Local\Programs\Python\Python38\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "C:\Users\93721\AppData\Local\Programs\Python\Python38\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\93721\AppData\Local\Programs\Python\Python38\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by jidle123** [comment]
重新下载安装了一下，还是不行

**Comment by zhzyker** [comment]
试试可以访问到这个接口嘛？
http://api.hostip.info/get_json.php

**Comment by jidle123** [comment]
唔，能访问，但貌似不是这个情况。
我是每次在设置--proxy-http的时候启动报这个错，但是我突然发现每次开机第一次启动的时候能挂上代理可以正常跑，但是第二次以后就代理报错。
感觉有点玄学......

**Comment by zhzyker** [comment]
问题太多了哈哈 等大改了

**Comment by 4White4** [comment]
也碰到了，求更新
