### ISSUE TITLE
报错啊，不知道啥情况

### ISSUE THREAD

**Issue by U188** [zhzyker/vulmap#9]
Traceback (most recent call last):
  File "C:\vulmap-main\vulmap.py", line 32, in <module>
    from Crypto.Cipher import AES
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38-32\lib\site-packages\Crypto\Cipher\__init__.py", line 27, in <module>
    from Crypto.Cipher._mode_ecb import _create_ecb_cipher
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38-32\lib\site-packages\Crypto\Cipher\_mode_ecb.py", line 35, in <module>
    raw_ecb_lib = load_pycryptodome_raw_lib("Crypto.Cipher._raw_ecb", """
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38-32\lib\site-packages\Crypto\Util\_raw_api.py", line 308, in load_pycryptodome_raw_lib
    raise OSError("Cannot load native module '%s': %s" % (name, ", ".join(attempts)))
OSError: Cannot load native module 'Crypto.Cipher._raw_ecb': Trying '_raw_ecb.cp38-win32.pyd': cannot load library 'C:\Users\Administrator\AppData\Local\Programs\Python\Python38-32\lib\site-packages\Crypto\Util\..\Cipher\_raw_ecb.cp38-win32.pyd': error 0x7e.  Additionally, ctypes.util.find_library() did not manage to locate a library called 'C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\site-packages\\Crypto\\Util\\..\\Cipher\\_raw_ecb.cp38-win32.pyd', Trying '_raw_ecb.pyd': cannot load library 'C:\Users\Administrator\AppData\Local\Programs\Python\Python38-32\lib\site-packages\Crypto\Util\..\Cipher\_raw_ecb.pyd': error 0xc1

**Comment by zhzyker** [comment]
盲猜你的pycryptodome模块出了点问题
